/* automatically generated by rust-bindgen 0.69.0 */

pub const TNUM_TSKID: i32 = 3;
pub const TSKID_tTask_rProcessor1Migratable_LogTask_Task: i32 = 1;
pub const TSKID_UART: i32 = 2;
pub const TSKID_LOOP: i32 = 3;
pub const TNUM_SEMID: i32 = 2;
pub const SEMID_tSemaphore_rProcessor1Migratable_SerialPort1_ReceiveSemaphore: i32 = 1;
pub const SEMID_tSemaphore_rProcessor1Migratable_SerialPort1_SendSemaphore: i32 = 2;
pub const TNUM_FLGID: i32 = 0;
pub const TNUM_DTQID: i32 = 1;
pub const DTQID_UART: i32 = 1;
pub const TNUM_PDQID: i32 = 0;
pub const TNUM_MTXID: i32 = 0;
pub const TNUM_SPNID: i32 = 0;
pub const TNUM_MPFID: i32 = 0;
pub const TNUM_CYCID: i32 = 0;
pub const TNUM_ALMID: i32 = 0;
pub const TNUM_ISRID: i32 = 2;
pub const ISRID_tISR_rProcessor1Migratable_SIOPortTarget1_ISRInstance: i32 = 1;
pub const ISRID_PRC2: i32 = 2;
pub const TNUM_INIRTN: i32 = 3;
pub const TNUM_TERRTN: i32 = 4;
