/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef sCheck_TECSGEN_H
#define sCheck_TECSGEN_H

/*
 * signature   :  sCheck
 * global name :  sCheck
 * context     :  task
 */

#ifndef TOPPERS_MACRO_ONLY

/* signature descriptor #_SD_# */
struct tag_sCheck_VDES {
    struct tag_sCheck_VMT *VMT;
};

/* signature function table #_SFT_# */
struct tag_sCheck_VMT {
    uint32_t       (*add__T)( const struct tag_sCheck_VDES *edp, uint32_t i, uint32_t j );
    void           (*sub__T)( const struct tag_sCheck_VDES *edp, int32_t i, int32_t j, int32_t* result );
    int32_t        (*sum__T)( const struct tag_sCheck_VDES *edp, const int32_t* array );
    void           (*copy__T)( const struct tag_sCheck_VDES *edp, const int32_t* input, int32_t** output );
};

/* signature descriptor #_SDES_# for dynamic join */
#ifndef Descriptor_of_sCheck_Defined
#define  Descriptor_of_sCheck_Defined
typedef struct { struct tag_sCheck_VDES *vdes; } Descriptor( sCheck );
#endif
#endif /* TOPPERS_MACRO_ONLY */

/* function id */
#define	FUNCID_SCHECK_ADD                      (1)
#define	FUNCID_SCHECK_SUB                      (2)
#define	FUNCID_SCHECK_SUM                      (3)
#define	FUNCID_SCHECK_COPY                     (4)

#endif /* sCheck_TECSGEN_H */
