/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#include "tCCall_tecsgen.h"
#include "tCCall_factory.h"

/* entry port descriptor type #_EDT_# */
/* eCEntry */
struct tag_tCCall_eCEntry_DES {
    const struct tag_sCheck_VMT *vmt;
    tCCall_IDX  idx;
};

/* entry port skelton function #_EPSF_# */
/* eCEntry */
uint32_t       tCCall_eCEntry_add_skel( const struct tag_sCheck_VDES *epd, uint32_t i, uint32_t j)
{
    struct tag_tCCall_eCEntry_DES *lepd
        = (struct tag_tCCall_eCEntry_DES *)epd;
    return tCCall_eCEntry_add( lepd->idx, i, j );
}
void           tCCall_eCEntry_sub_skel( const struct tag_sCheck_VDES *epd, int32_t i, int32_t j, int32_t* result)
{
    struct tag_tCCall_eCEntry_DES *lepd
        = (struct tag_tCCall_eCEntry_DES *)epd;
    tCCall_eCEntry_sub( lepd->idx, i, j, result );
}
int32_t        tCCall_eCEntry_sum_skel( const struct tag_sCheck_VDES *epd, const int32_t* array)
{
    struct tag_tCCall_eCEntry_DES *lepd
        = (struct tag_tCCall_eCEntry_DES *)epd;
    return tCCall_eCEntry_sum( lepd->idx, array );
}
void           tCCall_eCEntry_copy_skel( const struct tag_sCheck_VDES *epd, const int32_t* input, int32_t** output)
{
    struct tag_tCCall_eCEntry_DES *lepd
        = (struct tag_tCCall_eCEntry_DES *)epd;
    tCCall_eCEntry_copy( lepd->idx, input, output );
}

/* entry port skelton function table #_EPSFT_# */
/* eCEntry */
const struct tag_sCheck_VMT tCCall_eCEntry_MT_ = {
    tCCall_eCEntry_add_skel,
    tCCall_eCEntry_sub_skel,
    tCCall_eCEntry_sum_skel,
    tCCall_eCEntry_copy_skel,
};

/* entry port descriptor referenced by call port (differ from actual definition) #_CPEPD_# */
extern struct tag_sCheck_VDES RustEntry_eRustEntry_des;

extern struct tag_sCheck_VDES CEntry_eCEntry_des;

/* call port array #_CPA_# */


/* array of attr/var #_AVAI_# */
/* cell INIB #_INIB_# */
tCCall_INIB tCCall_INIB_tab[] = {
    /* cell: tCCall_CB_tab[0]:  CCall id=1 */
    {
        /* call port (INIB) #_CP_# */ 
        &RustEntry_eRustEntry_des,               /* cEntry #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        0,                                       /* id */
    },
    /* cell: tCCall_CB_tab[1]:  CCall2 id=2 */
    {
        /* call port (INIB) #_CP_# */ 
        &CEntry_eCEntry_des,                     /* cEntry #_CCP1_# */
        /* entry port #_EP_# */ 
        /* attribute(RO) */ 
        0,                                       /* id */
    },
};

/* entry port descriptor #_EPD_# */
extern const struct tag_tCCall_eCEntry_DES CCall_eCEntry_des;
const struct tag_tCCall_eCEntry_DES CCall_eCEntry_des = {
    &tCCall_eCEntry_MT_,
    &tCCall_INIB_tab[0],      /* INIB 3 */
};
extern const struct tag_tCCall_eCEntry_DES CCall2_eCEntry_des;
const struct tag_tCCall_eCEntry_DES CCall2_eCEntry_des = {
    &tCCall_eCEntry_MT_,
    &tCCall_INIB_tab[1],      /* INIB 3 */
};
