/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tCCall_TECSGEN_H
#define tCCall_TECSGEN_H

/*
 * celltype          :  tCCall
 * global name       :  tCCall
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  no
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  no
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sCheck_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tCCall_INIB {
    /* call port #_TCP_# */
    struct tag_sCheck_VDES const*cEntry; /* TCP_2 */
    /* call port #_NEP_# */ 
    /* attribute(RO) #_ATO_# */ 
    uint32_t       id;
}  tCCall_INIB;

/* CB not exist. CB corresponding to INIB #_DCI_# */
#define tCCall_CB_tab           tCCall_INIB_tab
#define tCCall_CB               tCCall_INIB
#define tag_tCCall_CB           tag_tCCall_INIB

/* singleton cell CB prototype declaration #_MCPB_# */
extern tCCall_INIB  tCCall_INIB_tab[];

/* celltype IDX type #_CTIX_# */
typedef const struct tag_tCCall_INIB *tCCall_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sCheck */
uint32_t     tCCall_eCEntry_add(tCCall_IDX idx, uint32_t i, uint32_t j);
void         tCCall_eCEntry_sub(tCCall_IDX idx, int32_t i, int32_t j, int32_t* result);
int32_t      tCCall_eCEntry_sum(tCCall_IDX idx, const int32_t* array);
void         tCCall_eCEntry_copy(tCCall_IDX idx, const int32_t* input, int32_t** output);
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

#define tCCall_ID_BASE              (1)  /* ID Base  #_NIDB_# */
#define tCCall_N_CELL               (2)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tCCall_VALID_IDX(IDX) (1)


/* celll CB macro #_GCB_# */
#define tCCall_GET_CELLCB(idx) (idx)

/* attr access  #_AAM_# */
#define tCCall_ATTR_id( p_that )	((p_that)->id)

#define tCCall_GET_id(p_that)	((p_that)->id)



#ifndef TECSFLOW
 /* call port function macro #_CPM_# */
#define tCCall_cEntry_add( p_that, i, j ) \
	  (p_that)->cEntry->VMT->add__T( \
	   (p_that)->cEntry, (i), (j) )
#define tCCall_cEntry_sub( p_that, i, j, result ) \
	  (p_that)->cEntry->VMT->sub__T( \
	   (p_that)->cEntry, (i), (j), (result) )
#define tCCall_cEntry_sum( p_that, array ) \
	  (p_that)->cEntry->VMT->sum__T( \
	   (p_that)->cEntry, (array) )
#define tCCall_cEntry_copy( p_that, input, output ) \
	  (p_that)->cEntry->VMT->copy__T( \
	   (p_that)->cEntry, (input), (output) )

#else  /* TECSFLOW */
#define tCCall_cEntry_add( p_that, i, j ) \
	  (p_that)->cEntry.add__T( \
 (i), (j) )
#define tCCall_cEntry_sub( p_that, i, j, result ) \
	  (p_that)->cEntry.sub__T( \
 (i), (j), (result) )
#define tCCall_cEntry_sum( p_that, array ) \
	  (p_that)->cEntry.sum__T( \
 (array) )
#define tCCall_cEntry_copy( p_that, input, output ) \
	  (p_that)->cEntry.copy__T( \
 (input), (output) )

#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eCEntry */
uint32_t       tCCall_eCEntry_add_skel( const struct tag_sCheck_VDES *epd, uint32_t i, uint32_t j);
void           tCCall_eCEntry_sub_skel( const struct tag_sCheck_VDES *epd, int32_t i, int32_t j, int32_t* result);
int32_t        tCCall_eCEntry_sum_skel( const struct tag_sCheck_VDES *epd, const int32_t* array);
void           tCCall_eCEntry_copy_skel( const struct tag_sCheck_VDES *epd, const int32_t* input, int32_t** output);

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tCCall_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tCCall_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tCCall_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tCCall_IDX


/* attr access macro (abbrev) #_AAMA_# */
#define ATTR_id              tCCall_ATTR_id( p_cellcb )


/* call port function macro (abbrev) #_CPMA_# */
#define cEntry_add( i, j ) \
          tCCall_cEntry_add( p_cellcb, i, j )
#define cEntry_sub( i, j, result ) \
          tCCall_cEntry_sub( p_cellcb, i, j, result )
#define cEntry_sum( array ) \
          tCCall_cEntry_sum( p_cellcb, array )
#define cEntry_copy( input, output ) \
          tCCall_cEntry_copy( p_cellcb, input, output )




/* entry port function macro (abbrev) #_EPM_# */
#define eCEntry_add      tCCall_eCEntry_add
#define eCEntry_sub      tCCall_eCEntry_sub
#define eCEntry_sum      tCCall_eCEntry_sum
#define eCEntry_copy     tCCall_eCEntry_copy

/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tCCall_N_CELL; (i)++ ){ \
       //(p_cb) = &tCCall_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tCCall_TECSGENH */
