/*
 * This file was automatically generated by tecsgen.
 * This file is not intended to be edited.
 */
#ifndef tCEntry_TECSGEN_H
#define tCEntry_TECSGEN_H

/*
 * celltype          :  tCEntry
 * global name       :  tCEntry
 * multi-domain      :  no
 * idx_is_id(actual) :  no(no)
 * singleton         :  no
 * has_CB            :  no
 * has_INIB          :  yes
 * rom               :  yes
 * CB initializer    :  no
 */

/* global header #_IGH_# */
#include "global_tecsgen.h"

/* signature header #_ISH_# */
#include "sCheck_tecsgen.h"

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/* cell INIB type definition #_CIP_# */
typedef const struct tag_tCEntry_INIB {
    /* call port #_NEP_# */ 
    /* attribute(RO) #_ATO_# */ 
    uint32_t       id;
}  tCEntry_INIB;

/* CB not exist. CB corresponding to INIB #_DCI_# */
#define tCEntry_CB_tab           tCEntry_INIB_tab
#define tCEntry_CB               tCEntry_INIB
#define tag_tCEntry_CB           tag_tCEntry_INIB

/* singleton cell CB prototype declaration #_MCPB_# */
extern tCEntry_INIB  tCEntry_INIB_tab[];

/* celltype IDX type #_CTIX_# */
typedef const struct tag_tCEntry_INIB *tCEntry_IDX;

/* prototype declaration of entry port function #_EPP_# */
/* sCheck */
uint32_t     tCEntry_eCEntry_add(tCEntry_IDX idx, uint32_t i, uint32_t j);
void         tCEntry_eCEntry_sub(tCEntry_IDX idx, int32_t i, int32_t j, int32_t* result);
int32_t      tCEntry_eCEntry_sum(tCEntry_IDX idx, const int32_t* array);
void         tCEntry_eCEntry_copy(tCEntry_IDX idx, const int32_t* input, int32_t** output);
#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

#define tCEntry_ID_BASE             (1)  /* ID Base  #_NIDB_# */
#define tCEntry_N_CELL              (1)  /*  number of cells  #_NCEL_# */

/* IDX validation macro #_CVI_# */
#define tCEntry_VALID_IDX(IDX) (1)


/* celll CB macro #_GCB_# */
#define tCEntry_GET_CELLCB(idx) (idx)

/* attr access  #_AAM_# */
#define tCEntry_ATTR_id( p_that )	((p_that)->id)

#define tCEntry_GET_id(p_that)	((p_that)->id)



#ifndef TECSFLOW
#else  /* TECSFLOW */
#endif /* TECSFLOW */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* prototype declaration of entry port function (referenced when VMT useless optimise enabled) #_EPSP_# */
/* eCEntry */
uint32_t       tCEntry_eCEntry_add_skel( const struct tag_sCheck_VDES *epd, uint32_t i, uint32_t j);
void           tCEntry_eCEntry_sub_skel( const struct tag_sCheck_VDES *epd, int32_t i, int32_t j, int32_t* result);
int32_t        tCEntry_eCEntry_sum_skel( const struct tag_sCheck_VDES *epd, const int32_t* array);
void           tCEntry_eCEntry_copy_skel( const struct tag_sCheck_VDES *epd, const int32_t* input, int32_t** output);

#ifndef TOPPERS_CB_TYPE_ONLY

#endif /* TOPPERS_CB_TYPE_ONLY */

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* TOPPERS_MACRO_ONLY */

#ifndef TOPPERS_CB_TYPE_ONLY

/* IDX validation macro (abbrev.) #_CVIA_# */
#define VALID_IDX(IDX)  tCEntry_VALID_IDX(IDX)


/* cell CB macro (abbrev) #_GCBA_# */
#define GET_CELLCB(idx)  tCEntry_GET_CELLCB(idx)

/* CELLCB type (abbrev) #_CCT_# */
#define CELLCB	tCEntry_CB

/* celltype IDX type (abbrev) #_CTIXA_# */
#define CELLIDX	tCEntry_IDX


/* attr access macro (abbrev) #_AAMA_# */
#define ATTR_id              tCEntry_ATTR_id( p_cellcb )





/* entry port function macro (abbrev) #_EPM_# */
#define eCEntry_add      tCEntry_eCEntry_add
#define eCEntry_sub      tCEntry_eCEntry_sub
#define eCEntry_sum      tCEntry_eCEntry_sum
#define eCEntry_copy     tCEntry_eCEntry_copy

/* iteration code (FOREACH_CELL) #_FEC_# */
#define FOREACH_CELL(i,p_cb)   \
    for( (i) = 0; (i) < tCEntry_N_CELL; (i)++ ){ \
       //(p_cb) = &tCEntry_CB_tab[i];

#define END_FOREACH_CELL   }

/* CB initialize macro #_CIM_# */
#endif /* TOPPERS_CB_TYPE_ONLY */

#ifndef TOPPERS_MACRO_ONLY

#endif /* TOPPERS_MACRO_ONLY */

#endif /* tCEntry_TECSGENH */
